name: A workflow to create a build jekyll site and push it to other branch of same repository
on:
  push:
    branches:
      - master:
  build:
    name: A job to create a build jekyll site and push it to other branch of same repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
      - uses: meitar/jekyll-builder-for-github-pages-action@master
        with:
          # Provide this action with your repository's `GH_PAGES_TOKEN`
          # "Secret" variable. This should be the value of a personal
          # access token granted, at a minimum, the `public_repo` and
          # the `repo_deployment` scopes needed to deploy to GH Pages.
          secret_gh_pages_api_token: ${{ secrets.GITHUB_TOKEN }}
