name: A workflow to create a build jekyll site from branch test and push it to /test path of master branch
on:
  push:
    branches:
    - test        
jobs:       
  build:
    name: A job to create a build jekyll site and push it to other branch of same repository
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/cache@v1
        id: cache
        with:
          path: /home/runner/work/vendor/bundle
          key: vendor_bundle_${{ runner.os }}-build-${{ env.cache-name }}-build_and_publish_to_other_branch
          restore-keys: |
            vendor_bundle_${{ runner.os }}-build-${{ env.cache-name }}-build_and_publish_to_other_branch
 
      - name: Checkout test branch
        uses: actions/checkout@master
        with:
          path: test
          ref: test

      - name: Checkout master branch
        uses: actions/checkout@master
        with:
          ref: master
          path: master

      - name: Create destination directory if not exist
        run: mkdir -p master/test

      - name: Change baseurl for test website
        run: sed -ri 's+^(baseurl.*) ""+\1 "/test"+g' test/_config.yml

#      - name: Jekyll Build
#        uses: gha-utilities/jekyll-build@v0.0.3
#        with:
#          jekyll_github_token: ${{ secrets.GITHUB_TOKEN }}
#          source: test
#          destination: master/test

      - name: Install bundler
        run: |
          #sudo apt-get install ruby-full build-essential zlib1g-dev
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          gem install bundler #jekyll
      - name: Install jekyll and dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          #sudo apt-get install ruby-full build-essential zlib1g-dev
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          cd test/
          bundle config path /home/runner/work/vendor/bundle
          bundle config --global --jobs 2
          bundle install
      - name: Build jekyll website
        run: |
          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"
          cd test/
          bundle exec jekyll build
          cd ..
          rm -rf master/test/*
          cp -r test/_site/* master/test/
      - name: Commit files
        working-directory: master
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          GIT_USER_NAME: 'Giovanni Sciortino'
          GIT_USER_EMAIL: 'giovannibattistasciortino@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New jekyll build from test branch to /test'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: master
          branch: 'master'
          github_token: ${{ secrets.GITHUB_TOKEN }}
