name: A workflow to create a build jekyll site and push it to other branch of same repository
on:
  push:
    branches:
    - master        
jobs:       
  build:
    name: A job to create a build jekyll site and push it to other branch of same repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master

      - name: Make build destination directory
        run: mkdir -vp ~/www

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@v0.0.3
        with:
          jekyll_github_token: ${{ secrets.GITHUB_TOKEN }}
          source: ./
          destination: ~/www
