name: A workflow to create a build jekyll site and push it to other branch of same repository
on:
  push:
    branches:
    - master        
jobs:       
  build:
    name: A job to create a build jekyll site and push it to other branch of same repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
        with:
          path: master

      - name: Make build destination directory
        run: mkdir -vp www 

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@v0.0.3
        with:
          jekyll_github_token: ${{ secrets.GITHUB_TOKEN }}
          source: master
          destination: www

      - name: Checkout jekyll_built branch
        uses: actions/checkout@master
        with:
          ref: jekyll_built
          path: jekyll_built
              
      - name: Copy built site to destination directory
        run: cp -ar master/www jekyll_built

      - name: Commit files
        working-directory: jekyll_built
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          GIT_USER_NAME: 'Giovanni Sciortino'
          GIT_USER_EMAIL: 'giovannibattistasciortino@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New jekyll built'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: jekyll_built
          github_token: ${{ secrets.GITHUB_TOKEN }}
